server:
  port: 8081

spring:
  application:
    name: finance

  datasource:
    url: jdbc:postgresql://localhost:5435/financedb
    username: joao
    password: joaodev

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  logging:
    level:
      org.springframework.security: DEBUG

app:
  jwt-secret: 'daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb5'
  jwt-expiration-milliseconds: 604800000